# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anson Yao's blog
email: yaoenxin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog of Anson Yao. Mainly about programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ansonyao.github.io/" # the base hostname & protocol for your site
github_username:  ansonyao

# Build settings
markdown: kramdown
